// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tagatac/typedstream-go (interfaces: Unarchiver)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_unarchiver.go -package=mock_typedstream github.com/tagatac/typedstream-go Unarchiver
//

// Package mock_typedstream is a generated GoMock package.
package mock_typedstream

import (
	reflect "reflect"

	typedstream "github.com/tagatac/typedstream-go"
	gomock "go.uber.org/mock/gomock"
)

// MockUnarchiver is a mock of Unarchiver interface.
type MockUnarchiver struct {
	ctrl     *gomock.Controller
	recorder *MockUnarchiverMockRecorder
	isgomock struct{}
}

// MockUnarchiverMockRecorder is the mock recorder for MockUnarchiver.
type MockUnarchiverMockRecorder struct {
	mock *MockUnarchiver
}

// NewMockUnarchiver creates a new mock instance.
func NewMockUnarchiver(ctrl *gomock.Controller) *MockUnarchiver {
	mock := &MockUnarchiver{ctrl: ctrl}
	mock.recorder = &MockUnarchiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnarchiver) EXPECT() *MockUnarchiverMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockUnarchiver) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockUnarchiverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUnarchiver)(nil).Close))
}

// DecodeAll mocks base method.
func (m *MockUnarchiver) DecodeAll() ([]*typedstream.TypedGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeAll")
	ret0, _ := ret[0].([]*typedstream.TypedGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeAll indicates an expected call of DecodeAll.
func (mr *MockUnarchiverMockRecorder) DecodeAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeAll", reflect.TypeOf((*MockUnarchiver)(nil).DecodeAll))
}

// DecodeAnyValue mocks base method.
func (m *MockUnarchiver) DecodeAnyValue(expectedEncoding []byte) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeAnyValue", expectedEncoding)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeAnyValue indicates an expected call of DecodeAnyValue.
func (mr *MockUnarchiverMockRecorder) DecodeAnyValue(expectedEncoding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeAnyValue", reflect.TypeOf((*MockUnarchiver)(nil).DecodeAnyValue), expectedEncoding)
}

// DecodeArray mocks base method.
func (m *MockUnarchiver) DecodeArray(elemType []byte, length int) (*typedstream.Array, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeArray", elemType, length)
	ret0, _ := ret[0].(*typedstream.Array)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeArray indicates an expected call of DecodeArray.
func (mr *MockUnarchiverMockRecorder) DecodeArray(elemType, length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeArray", reflect.TypeOf((*MockUnarchiver)(nil).DecodeArray), elemType, length)
}

// DecodeDataObject mocks base method.
func (m *MockUnarchiver) DecodeDataObject() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeDataObject")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeDataObject indicates an expected call of DecodeDataObject.
func (mr *MockUnarchiverMockRecorder) DecodeDataObject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeDataObject", reflect.TypeOf((*MockUnarchiver)(nil).DecodeDataObject))
}

// DecodePropertyList mocks base method.
func (m *MockUnarchiver) DecodePropertyList() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodePropertyList")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodePropertyList indicates an expected call of DecodePropertyList.
func (mr *MockUnarchiverMockRecorder) DecodePropertyList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodePropertyList", reflect.TypeOf((*MockUnarchiver)(nil).DecodePropertyList))
}

// DecodeSingleRoot mocks base method.
func (m *MockUnarchiver) DecodeSingleRoot() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeSingleRoot")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeSingleRoot indicates an expected call of DecodeSingleRoot.
func (mr *MockUnarchiverMockRecorder) DecodeSingleRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeSingleRoot", reflect.TypeOf((*MockUnarchiver)(nil).DecodeSingleRoot))
}

// DecodeTypedValues mocks base method.
func (m *MockUnarchiver) DecodeTypedValues() (*typedstream.TypedGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeTypedValues")
	ret0, _ := ret[0].(*typedstream.TypedGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeTypedValues indicates an expected call of DecodeTypedValues.
func (mr *MockUnarchiverMockRecorder) DecodeTypedValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeTypedValues", reflect.TypeOf((*MockUnarchiver)(nil).DecodeTypedValues))
}

// DecodeValueOfType mocks base method.
func (m *MockUnarchiver) DecodeValueOfType(typeEncoding []byte) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeValueOfType", typeEncoding)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeValueOfType indicates an expected call of DecodeValueOfType.
func (mr *MockUnarchiverMockRecorder) DecodeValueOfType(typeEncoding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeValueOfType", reflect.TypeOf((*MockUnarchiver)(nil).DecodeValueOfType), typeEncoding)
}

// DecodeValuesOfTypes mocks base method.
func (m *MockUnarchiver) DecodeValuesOfTypes(typeEncodings ...[]byte) ([]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range typeEncodings {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DecodeValuesOfTypes", varargs...)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeValuesOfTypes indicates an expected call of DecodeValuesOfTypes.
func (mr *MockUnarchiverMockRecorder) DecodeValuesOfTypes(typeEncodings ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeValuesOfTypes", reflect.TypeOf((*MockUnarchiver)(nil).DecodeValuesOfTypes), typeEncodings...)
}
